### ISSUE TITLE
[ENH] make prfanalyze/base/run.py more flexible

### ISSUE THREAD

**Issue by garikoitz** [vistalab/PRFmodel#22]
This line ` (testdat, x0, y0, th, sigmin, sigmaj, pred) = [np.squeeze(u) for u in dat]` requires that the columns are always in the same order and that there are always the same elements. 

I am going to edit pmModelFit for now to remove other outputs and make the order is always the same, but this won't be the reality when we start using other options, `dat` will have multiple columns. I think the routine should read fieldnames regardless the count and order and process them.

**Comment by noahbenson** [comment]
Should be able to extract the names of the parameters from the estimates.mat file (which is already loaded in run.py); if so, can just use these instead of a concrete ordering.

**Comment by noahbenson** [comment]
So after playing around a bit, it appears that there isn't currently a way to get the table column names from `estimates.mat` in Python. Would it be possible to save the tables as struct's instead? E.g., instead of saving out a table with colums A, B, C, save out a struct "estimates" with `estimates.A`, `estimates.B`, `estimates.C`, etc.? This would make it much easier to read/manage in python.

Alternately, I can extract the columns without the column names, so if the column names were saved in a separate cell array in estimates.mat, I could get them there.

**Comment by garikoitz** [comment]
I can save struct, but wouldn’t it better to save it as json?

**Comment by noahbenson** [comment]
I think a JSON is fine and more portable, but the files might be very large. Can you maybe check what the file size is for a non-small set of sample voxels? I'm worried that the JSON alone may be 100s of megabytes in this case, but might not be too bad.

**Comment by garikoitz** [comment]
For example, the json file for a 31185 time series simulation is 28Mb. But
this is not for the results, this is for the whole set of parameters. The
results.mat for this  analysis was 996Kb and the results.json is 7.4Mb.

It should be ok right??

**Comment by noahbenson** [comment]
Oh, sure; I was thinking that the estimates would be the problem--they are basically the whole time-series, right? So if we estimate 1000 voxels with 120 TRs, we're looking at 120,000 floating points in text. I guess that's sill just megabytes most likely. So sure, if you can write them as a JSON, I can fix the prfanalyze code use the JSONs instead of the .mat files easily.

**Comment by garikoitz** [comment]
Noah, II was just looking at this, but I realized that the writing is being
done in prfanalyze_tool.m.

I am going to edit the prfanalyze_afni.m, prfanalyze_aprf.m,
prfanalyze_vista.m so that in addition to the .mat it writes the
estimates.json file.

So, the output will be:
- results.mat: this is the output from the tool, different values per each
tool. I think it is good that it gets written.
- estimates.mat: the same one we had, with "standardized" columns.
- (new) estimates.json: the same as estimates.mat but in json

does it sound right? you'll need to change the other files after this, is
that ok?

**Comment by garikoitz** [comment]
Small things:
I am running the whole pipeline with the new options.
I made a small edit to build_all.sh, now if no option is passed, it won't
do --no-cache, if we want to do --no-cache we need to explicitly say
./build_all.sh --no-cache
I didn't want to risk going the no-cache option mostly because of afni...
right now prfanalyze-afni is based on nben docker


Proposed small change:
1./ I think this two calls should write out the config file with a message.
The first call does nothing.
      # ./prfanalyze.sh vista $TEST2
      # ./prfanalyze.sh vista $TEST2 empty

2./ The name of the file to be consistent with the other gears, it should
be prfanalyze-config-defaults.json

3./ oh, and I just realized that it created it as a dir, and only root...
drwxr-xr-x  2 root   root 4.0K Jan 14 13:28 config.json/

Could you fix this please? Meanwhile I am going to try to use the defaults
we already had to make all the dockers run

thanks!
Gari

**Comment by garikoitz** [comment]
Sorry, another one, it cannot find the .tsv file because it is writing it
with double __ (I mean, in disk it exists the correct one with only one _)

glerma@black
:/data/localhome/glerma/toolboxes/PRFmodel/gear/prfanalyze:(master)$
# ./prfanalyze.sh vista $TEST2
/data/localhome/glerma/toolboxes/PRFmodel/local/test2/prfanalyze-vista-config-test2.json
Could not load events file:
/flywheel/v0/input/BIDS/sub-test2/ses-sess2/func/sub-test2_ses-sess2__events.tsv
